spring.shell.interactive.enabled=false
spring.shell.script.enabled=false
spring.shell.noninteractive.enabled=false
spring.main.banner-mode=off
spring.main.web-application-type=none
logging.level.root=off
spring.ai.mcp.server.name=jns
spring.ai.mcp.server.version=0.1.1
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.stdio=true
